import os from 'os';
import fs from 'fs';
import path from 'path';
import enquirer from "enquirer";
import { P2PNode } from 'core';
import { importKeyStores } from './keystore/import.js';

export default {
  command: 'import',

  describe: 'The directory flag provides a convenient \
  method for importing a directory of keys generated by the eth2-deposit-cli \
  Ethereum Foundation utility. ',

  examples: [
    {
      command: "ringer import --keystores $HOME/eth2.0-deposit-cli/validator_keys",
      description: "Import validator keystores generated with the Ethereum Foundation Staking Launchpad",
    },
  ],

  /**
   * @param yargs
   */
  builder (yargs) {
    return yargs
      .option('keystores', {
        type: 'string',
        desc: 'Path to the keystores generated with the Ethereum Foundation Staking Launchpad',
        require: true
      })
      .option('password', {
        type: 'string',
        desc: 'Path to the keystores password.txt file'
      })
  },

  /**
   * @param {object} argv
   */
  async handler (argv) {
    const keyStorePath = argv.keystores;
    await importKeyStores(keyStorePath);
  }
}
